/* Pass 2: persistent Michelson stage backed by the shared N3 teaching model. */
(function(){'use strict';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0));
function mount(host,options={}){
 const ac=new AbortController(),clock=window.FTIRTimeline?.create?.(),po=window.FTIROpticsTeaching||{sample:()=>({}),geometry:()=>({moving:[330,190]})};
 const s={beat:0,progress:1};let dead=false,busy=false,autoTimer=null,suspended=document.visibilityState==='hidden',n4=false,n4Beat=0,n4Progress=1,n4From=0,n4Target=0,n4Tween={v:1};
 host.innerHTML=`<div class="po-viewport"><section class="po-stage" tabindex="-1" aria-label="Michelson presentation stage"><div class="po-top"><span>FTIR · 从信号到光谱</span><span>3 / 09</span></div><header><p>MICHELSON · 波数编码</p><h1>Michelson 如何编码波数？</h1></header><div class="po-canvas"><svg class="po-svg" viewBox="0 0 1600 700" role="img" aria-label="光源、分束器、固定镜、动镜、探测器和光程差记录"><g class="po-instrument" transform="translate(120 82) scale(1.35)"><path class="po-ref" d="M200 190V60M200 190H400M200 190V315"/><path data-beam="input" class="po-beam"/><path data-beam="fixed" class="po-beam"/><path data-beam="fixed-return" class="po-beam po-return"/><path data-beam="moving" class="po-beam"/><path data-beam="moving-return" class="po-beam po-return"/><path data-beam="output" class="po-beam"/><g data-part="directions" class="po-directions"><path d="M90 190h28"/><path d="M194 145v-25"/><path d="M206 96v25"/><path d="M240 184h28"/><path d="M322 196h-28"/><path d="M200 250v28"/></g><circle cx="55" cy="190" r="13" class="po-source"/><text x="55" y="231">光源</text><path d="M174 216L226 164" class="po-split"/><text x="113" y="144">分束器</text><path d="M175 60H225M178 53H222" class="po-mirror"/><text x="200" y="32">固定镜</text><g data-moving><path class="po-mirror"/><text x="330" y="139">动镜</text></g><g data-part="displacement"><path data-dimension class="po-dimension"/><text data-dx y="254"/></g><rect x="179" y="307" width="42" height="25" rx="3" class="po-detector"/><text x="200" y="364">探测器</text><text data-response x="260" y="312" class="po-small">1000 cm⁻¹ 响应</text><text data-power x="260" y="342" class="po-value"/><path data-link class="po-link"/><g class="po-explain"><path data-extra1 class="po-extra"/><path data-extra2 class="po-extra"/><path data-bracket class="po-bracket"/><text data-extra-label1/><text data-extra-label2/><text data-formula>Δδ = 2Δx</text><text data-definition>OPD：两臂往返光程之差</text></g></g><g class="po-record"><text class="po-record-title" x="850" y="70">探测器记录 · 归一化功率</text><path class="po-axis" d="M850 650H1480"/><path class="po-tick" d="M850 642v16M1165 642v16M1480 642v16"/><text x="850" y="680">光程差 OPD / μm</text><g class="po-track po-track-1000"><text x="850" y="225">1000 cm⁻¹</text><path class="po-track-axis" d="M850 245V390H1480"/><text x="838" y="255">1</text><text x="838" y="395">0</text><path data-trace1000 class="po-trace"/><circle data-dot1000 class="po-dot"/></g><g class="po-track po-track-3000"><text x="850" y="465">3000 cm⁻¹</text><path class="po-track-axis" d="M850 485V630H1480"/><text x="838" y="495">1</text><text x="838" y="635">0</text><path data-trace3000 class="po-trace po-gold"/><circle data-dot3000 class="po-dot po-gold"/></g><path data-cursor class="po-cursor"/><text data-record-note x="1165" y="560" text-anchor="middle"/></g></svg></div><p class="po-takeaway" aria-live="polite"/><div class="po-beat" aria-live="polite"/></section></div>`;
 const q=x=>host.querySelector(x),part=n=>q('[data-beam="'+n+'"]'),moving=q('[data-moving]'),power=(w,d)=>po.power?po.power(w,d):(1+Math.cos(2*Math.PI*w*d*1e-4))/2;
 function resize(){q('.po-stage').style.transform=`translate(-50%, -50%) scale(${Math.max(.01,Math.min(innerWidth/1600,innerHeight/900))})`;}
 function trackPoint(track,w,opd){const y0=track===1?390:630;return{x:850+opd*63,y:y0-power(w,opd)*145};}
 function curve(track,w,upto){const limit=clamp(upto)*10;let d='';for(let i=0;i<=180;i++){const opd=i*10/180;if(opd>limit+1e-8)break;const pt=trackPoint(track,w,opd);d+=`${i?'L':'M'}${pt.x} ${pt.y}`;}return d;}
 const show=(el,on)=>{const value=on?1:0;el.style.opacity=String(value);el.style.visibility=value?'visible':'hidden';};
 function render(){if(n4){renderN4();return;}q('.po-stage').removeAttribute('data-n4');q('.po-track-1000')?.querySelectorAll('text').forEach(e=>e.style.display='');q('.po-track-3000')?.querySelectorAll('text').forEach(e=>e.style.display='');q('.po-axis')?.setAttribute('d','M850 650H1480');q('.po-record-title').textContent='探测器记录 · 归一化功率';q('[data-cursor]')?.style.removeProperty('opacity');const d=po.sample(s.beat,s.progress),g=po.geometry(d.mirrorUm),x=g.moving?.[0]??g.mirrorX??330,p1=d.power1000??power(1000,d.opdUm),p3=d.power3000??power(3000,d.opdUm),layout=clamp(d.layout),focus=clamp(d.focus),instrument=q('.po-instrument');
  instrument.style.opacity=s.beat>=2?String(1-.28*focus):'1';instrument.setAttribute('transform',`translate(${420-layout*350} ${55+layout*27}) scale(${1.65-layout*.42})`);q('.po-stage').dataset.beat=String(s.beat);q('.po-stage').dataset.progress=Number(s.progress).toFixed(4);q('.po-stage').dataset.suspended=String(suspended);
  part('input').setAttribute('d','M68 190H200');part('fixed').setAttribute('d','M200 190V60');part('fixed-return').setAttribute('d','M200 60V190');part('moving').setAttribute('d',`M200 190H${x}`);part('moving-return').setAttribute('d',`M${x} 190H200`);part('output').setAttribute('d','M200 190V307');moving.setAttribute('transform',`translate(${x-330} 0)`);moving.querySelector('path').setAttribute('d','M330 163V217');
  q('[data-dimension]').setAttribute('d',`M330 227v9M330 232H${x}M${x} 227v9`);q('[data-dx]').setAttribute('x',(330+x)/2);q('[data-dx]').textContent=s.beat>=1?`Δx = ${d.mirrorUm.toFixed(2)} μm`:'';q('[data-power]').textContent=(s.beat>=5?p3:p1).toFixed(2);q('[data-response]').textContent=(s.beat>=5?'3000':'1000')+' cm⁻¹ 响应';
  const out=clamp(d.outbound),ret=clamp(d.return);q('[data-extra1]').setAttribute('d',`M330 184H${330+(x-330)*out}`);q('[data-extra2]').setAttribute('d',`M330 196H${330+(x-330)*ret}`);q('[data-extra-label1]').setAttribute('x',330+(x-330)*out/2);q('[data-extra-label1]').setAttribute('y',178);q('[data-extra-label1]').textContent=out>0?'+ Δx':'';q('[data-extra-label2]').setAttribute('x',330+(x-330)*ret/2);q('[data-extra-label2]').setAttribute('y',216);q('[data-extra-label2]').textContent=ret>0?'+ Δx':'';q('[data-formula]').setAttribute('x',560);q('[data-formula]').setAttribute('y',250);q('[data-definition]').setAttribute('x',560);q('[data-definition]').setAttribute('y',280);show(q('.po-explain'),s.beat>=2&&s.beat<4);q('[data-extra1]').style.opacity=String(out);q('[data-extra2]').style.opacity=String(ret);q('[data-extra-label1]').style.opacity=String(out);q('[data-extra-label2]').style.opacity=String(ret);q('[data-bracket]').setAttribute('d',`M330 205V220H${x}V205`);q('[data-formula]').style.opacity=String(d.formula);q('[data-definition]').style.opacity=String(d.formula);
  q('[data-link]').setAttribute('d',`M200 315H${320+layout*340}`);q('[data-link]').style.opacity=s.beat>=4?String(layout):'0';show(q('.po-record'),s.beat>=4);show(q('.po-track-3000'),s.beat>=5&&(d.trace3000||0)>0);q('[data-trace1000]').setAttribute('d',curve(1,1000,d.trace1000||0));q('[data-trace3000]').setAttribute('d',curve(3,3000,d.trace3000||0));const c1=trackPoint(1,1000,d.opdUm),c3=trackPoint(3,3000,d.opdUm);q('[data-dot1000]').setAttribute('cx',c1.x);q('[data-dot1000]').setAttribute('cy',c1.y);q('[data-dot3000]').setAttribute('cx',c3.x);q('[data-dot3000]').setAttribute('cy',c3.y);q('[data-cursor]').setAttribute('d',`M${c1.x} 95V650`);q('[data-record-note]').textContent='';
  const record=q('.po-record');if(!q('[data-opd-ticks]')){const ns='http://www.w3.org/2000/svg',ticks=document.createElementNS(ns,'text');ticks.dataset.opdTicks='1';ticks.setAttribute('x','1165');ticks.setAttribute('y','675');ticks.setAttribute('text-anchor','middle');record.appendChild(ticks);}q('[data-opd-ticks]').textContent='0　　　 5　　　 10';
  q('.po-takeaway').textContent=['两路返回后在分束器重合，输出送往探测器。','只移动动镜，固定臂不变；探测响应同步改变。','动臂去程与回程各增加 Δx。','两段新增光程合并为 OPD：Δδ = 2Δx。','同一探测器记录随 OPD 扫描逐点形成。','相同 OPD 下，高波数留下更密的周期。'][s.beat];q('.po-beat').textContent=['观察','移动镜','往返','命名 OPD','记录','比较'][s.beat];}
 function n4Path(series){if(!series?.xs?.length)return '';const lo=series.xs[0],hi=series.xs[series.xs.length-1],span=hi-lo||1;let d='';for(let i=0;i<series.xs.length;i+=Math.max(1,Math.floor(series.xs.length/900))){const x=850+(series.xs[i]-lo)/span*630,y=390-series.ys[i]*58;d+=(d?'L':'M')+x.toFixed(2)+' '+y.toFixed(2);}return d;}
 function renderN4(){const model=window.FTIRInterferogramTeaching;if(!model)return;const broad=n4Beat>=4,from=Math.min(3,n4Beat),to=Math.min(3,n4Beat+1),record=broad?model.getRecord('broadband'):model.getRecord(Math.max(1,to)),view=broad?model.visibleSeries(record,-80,80,'peak'):model.mixedSeries(Math.max(0,from),Math.max(1,to),n4Beat<3?n4Progress:1),stage=q('.po-stage'),instrument=q('.po-instrument'),recordGroup=q('.po-record');if(!q('[data-opd-ticks]')){const ticks=document.createElementNS('http://www.w3.org/2000/svg','text');ticks.dataset.opdTicks='1';ticks.setAttribute('x','1165');ticks.setAttribute('y','445');ticks.setAttribute('text-anchor','middle');recordGroup.appendChild(ticks);}stage.dataset.n4='true';stage.dataset.beat=String(n4Beat);stage.dataset.progress=(n4Beat<3?n4Progress:1).toFixed(4);stage.dataset.recordId=record.id;stage.dataset.recordProvenance=record.provenance||'';instrument.style.opacity='.24';instrument.setAttribute('transform','translate(35 55) scale(1.05)');q('.po-stage h1').textContent='多个波数如何形成干涉图？';q('.po-takeaway').textContent=['保留一个波数的交流信号，扩大观察范围。','加入 1700 cm⁻¹，SUM 随真实加权记录更新。','加入 3000 cm⁻¹，三个周期共同形成 SUM。','贡献线淡出，SUM 扩展并命名为 INTERFEROGRAM。','切换到真实宽带记录，显示 OPD −80…80 μm。','ZPD 位于 δ=0；理想零相位时出现 centerburst。'][n4Beat];q('.po-beat').textContent=['handoff','+1700','+3000','INTERFEROGRAM','宽带记录','ZPD / centerburst'][n4Beat];q('[data-response]').textContent='交流信号 / 相对单位（去基线并归一化）';q('[data-power]').textContent='';q('[data-dx]').textContent='';q('[data-link]').style.opacity='0';show(q('.po-record'),1);show(q('.po-track-3000'),0);q('[data-record-note]').textContent='';
  const sum=q('[data-trace1000]');sum.setAttribute('d',n4Path(view));sum.style.opacity='1';sum.style.stroke='#176b91';q('.po-axis').setAttribute('d','M850 220V430H1480');q('.po-track-1000').querySelectorAll('text').forEach(e=>e.style.display='none');q('.po-track-3000').querySelectorAll('text').forEach(e=>e.style.display='none');let paths=[...recordGroup.querySelectorAll('[data-n4-comp]')];while(paths.length<3){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.dataset.n4Comp=String(paths.length+1);p.setAttribute('class','po-trace');recordGroup.appendChild(p);paths.push(p);}paths.forEach((p,i)=>{const active=!broad&&i<Math.min(3,to);if(!active){p.setAttribute('d','');p.style.opacity='0';return;}const cur=model.componentSeries(i,-20,20);p.setAttribute('d',n4Path(cur));p.style.stroke=['#89b4ef','#f3c96d','#d29aa5'][i];p.style.opacity=String(n4Beat===3?.18:n4Beat<3?.7:0);});q('[data-dot1000]').style.opacity='0';q('[data-dot3000]').style.opacity='0';q('[data-cursor]').setAttribute('d',broad?`M${850+630/2} 220V430`:'M1165 220V430');q('[data-cursor]').style.opacity=n4Beat===5?'1':'0';q('[data-opd-ticks]')&&(q('[data-opd-ticks]').textContent=broad?'−80　　　 0　　　 80':'−20　　　 0　　　 20');q('.po-record-title').textContent=broad?'宽带探测器记录 · 交流信号':'探测器记录 · SUM 交流信号';q('.po-record-title').style.fontSize='24px';}
 function enterN4(){n4=true;n4Beat=0;n4Progress=1;stop();render();}
 function exitN4(){n4=false;n4Beat=0;Object.assign(s,{beat:5,progress:1});render();}
 function modelRecord(){const model=window.FTIRInterferogramTeaching;return model?.getRecord(n4Beat>=4?'broadband':Math.max(1,Math.min(3,n4Beat+1)))||null;}
 function stop(){clock?.pause?.();clock?.reset?.();busy=false;clearInterval(autoTimer);autoTimer=null;}
 function toggleAuto(){if(autoTimer){clearInterval(autoTimer);autoTimer=null;return false;}autoTimer=setInterval(()=>{if(!dead&&!suspended&&!busy)advance();},2600);return true;}
 function tween(duration,done){busy=true;if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches||!clock?.to){s.progress=1;render();busy=false;done();return;}clock.to(s,{progress:1,duration,ease:'none',onUpdate:render,onComplete:()=>{busy=false;done();}});}
 function advance(){if(dead||document.visibilityState==='hidden')return;if(suspended){suspended=false;clock?.resume?.();return;}if(busy)return;if(n4){if(n4Beat<5){n4From=n4Beat;n4Target=n4Beat+1;n4Tween.v=0;n4Progress=0;busy=true;if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches||!clock?.to){n4Beat=n4Target;n4Progress=1;busy=false;render();}else clock.to(n4Tween,{v:1,duration:.7,ease:'none',onUpdate:()=>{n4Progress=n4Tween.v;render();},onComplete:()=>{n4Beat=n4Target;n4Progress=1;busy=false;render();}});}else options.onNext?.({record:modelRecord(),recordId:q('.po-stage').dataset.recordId,provenance:q('.po-stage').dataset.recordProvenance});return;}if(s.beat>=5){enterN4();return;}s.beat++;s.progress=0;render();tween(s.beat===2?.9:s.beat===3?.65:s.beat>=4?1:.8,render);}
 function prev(){if(busy)return;if(n4){if(n4Beat>0){n4Beat--;render();}else exitN4();return;}if(s.beat>0){stop();s.beat--;s.progress=1;render();}else options.onBack?.();}function reset(){stop();suspended=false;if(n4){n4Beat=0;render();return;}Object.assign(s,{beat:0,progress:1});render();}
 function key(e){if(dead||e.repeat||e.target.matches?.('button,input,textarea,a,select,[contenteditable=true]'))return;if(e.key===' '||e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();advance();}else if(e.key==='ArrowLeft'){e.preventDefault();e.stopPropagation();prev();}else if(e.key.toLowerCase()==='r'){e.preventDefault();e.stopPropagation();reset();}else if(e.key.toLowerCase()==='a'){e.preventDefault();e.stopPropagation();toggleAuto();}}
 const stage=q('.po-stage');stage.addEventListener('click',e=>{if(!e.target.closest('button,input,label'))advance();},{signal:ac.signal});document.addEventListener('keydown',key,{signal:ac.signal});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){suspended=true;clock?.pause?.();}else if(suspended)render();},{signal:ac.signal});window.addEventListener('resize',resize,{signal:ac.signal});resize();if(options.startN4)enterN4();else render();stage.focus({preventScroll:true});return{dispose(){dead=true;stop();clock?.kill?.();ac.abort();host.innerHTML='';},next:advance,prev,replay:reset,getState:()=>({...s,suspended,n4,n4Beat,record:modelRecord(),recordId:n4?q('.po-stage')?.dataset.recordId:null})};}
 window.FTIRPresentationOptics={mount};}());
